pipeline {
    agent any

    environment {
        // Set up Python environment if needed (example uses a virtual environment)
        VENV_DIR = 'venv'
    }

    stages {
        stage('Setup') {
            steps {
                script {
                    // Install Python and dependencies (use your preferred setup)
                    sh 'python3 -m venv ${VENV_DIR}'
                    sh '${VENV_DIR}/bin/pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    // Run tests using pytest and generate the HTML report
                    sh '${VENV_DIR}/bin/pytest tests/test_reqres_api.py --maxfail=5 --disable-warnings --html=reports/report.html'
                }
            }
        }

        stage('Archive Test Report') {
            steps {
                // Archive the test report generated by pytest-html
                archiveArtifacts artifacts: 'reports/report.html', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            // Clean up if necessary, e.g., removing virtual environment
            cleanWs()
        }
    }
}